# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param power.BramSDPPropagationFix 1
set_param chipscope.maxJobs 4
set_param power.enableUnconnectedCarry8PinPower 1
set_param power.enableCarry8RouteBelPower 1
set_param power.enableLutRouteBelPower 1
create_project -in_memory -part xczu7ev-ffvc1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {F:/4th year 1st term/DIGITAL/Project/FFT_WRAPPER/FFT_WRAPPER/FFT_WRAPPER.cache/wt} [current_project]
set_property parent.project_path {F:/4th year 1st term/DIGITAL/Project/FFT_WRAPPER/FFT_WRAPPER/FFT_WRAPPER.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zcu106:part0:2.4 [current_project]
set_property ip_output_repo {f:/4th year 1st term/DIGITAL/Project/FFT_WRAPPER/FFT_WRAPPER/FFT_WRAPPER.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {{F:/4th year 1st term/DIGITAL/Project/FFT_WRAPPER/FFT_WRAPPER/fft32_round_and_sat.sv}}
read_verilog -library xil_defaultlib {
  {F:/4th year 1st term/DIGITAL/Project/FFT_WRAPPER/FFT_WRAPPER/fft32_butterfly.v}
  {F:/4th year 1st term/DIGITAL/Project/FFT_WRAPPER/FFT_WRAPPER/fft32_complex_mult.v}
  {F:/4th year 1st term/DIGITAL/Project/FFT_WRAPPER/FFT_WRAPPER/fft32_control_unit.v}
  {F:/4th year 1st term/DIGITAL/Project/FFT_WRAPPER/FFT_WRAPPER/fft32_mac_unit.v}
  {F:/4th year 1st term/DIGITAL/Project/FFT_WRAPPER/FFT_WRAPPER/fft32_mux5x1.v}
  {F:/4th year 1st term/DIGITAL/Project/FFT_WRAPPER/FFT_WRAPPER/fft32_mux_selection.v}
  {F:/4th year 1st term/DIGITAL/Project/FFT_WRAPPER/FFT_WRAPPER/fft32_register_bank.v}
  {F:/4th year 1st term/DIGITAL/Project/FFT_WRAPPER/FFT_WRAPPER/fft32_top.v}
  {F:/4th year 1st term/DIGITAL/Project/FFT_WRAPPER/FFT_WRAPPER/fft32_w_imag_rom.v}
  {F:/4th year 1st term/DIGITAL/Project/FFT_WRAPPER/FFT_WRAPPER/fft32_w_mux_selection.v}
  {F:/4th year 1st term/DIGITAL/Project/FFT_WRAPPER/FFT_WRAPPER/fft32_w_real_rom.v}
  {F:/4th year 1st term/DIGITAL/Project/FFT_WRAPPER/FFT_WRAPPER/FFT_WRAPPER.srcs/sources_1/new/FFT_WRAPPER.v}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{F:/4th year 1st term/DIGITAL/Project/FFT_WRAPPER/FFT_WRAPPER/FFT_WRAPPER.srcs/constrs_2/new/cons.xdc}}
set_property used_in_implementation false [get_files {{F:/4th year 1st term/DIGITAL/Project/FFT_WRAPPER/FFT_WRAPPER/FFT_WRAPPER.srcs/constrs_2/new/cons.xdc}}]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top FFT_WRAPPER -part xczu7ev-ffvc1156-2-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef FFT_WRAPPER.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file FFT_WRAPPER_utilization_synth.rpt -pb FFT_WRAPPER_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
