# Clock
set_property PACKAGE_PIN K21 [get_ports clk]
set_property IOSTANDARD LVCMOS18 [get_ports clk]
create_clock -period 10.0 [get_ports clk]

# Reset
set_property PACKAGE_PIN P20 [get_ports rst_n]
set_property IOSTANDARD LVCMOS18 [get_ports rst_n]

# Enable
set_property PACKAGE_PIN N21 [get_ports enable]
set_property IOSTANDARD LVCMOS18 [get_ports enable]

# Data In [7:0]
set_property PACKAGE_PIN M21 [get_ports {data_in[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[0]}]
set_property PACKAGE_PIN L20 [get_ports {data_in[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[1]}]
set_property PACKAGE_PIN K20 [get_ports {data_in[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[2]}]
set_property PACKAGE_PIN J19 [get_ports {data_in[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[3]}]
set_property PACKAGE_PIN J20 [get_ports {data_in[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[4]}]
set_property PACKAGE_PIN H20 [get_ports {data_in[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[5]}]
set_property PACKAGE_PIN G20 [get_ports {data_in[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[6]}]
set_property PACKAGE_PIN F20 [get_ports {data_in[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[7]}]

# Data Out [12:0]
set_property PACKAGE_PIN C22 [get_ports {data_out[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_out[0]}]
set_property PACKAGE_PIN D22 [get_ports {data_out[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_out[1]}]
set_property PACKAGE_PIN E22 [get_ports {data_out[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_out[2]}]
set_property PACKAGE_PIN F21 [get_ports {data_out[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_out[3]}]
set_property PACKAGE_PIN G22 [get_ports {data_out[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_out[4]}]
set_property PACKAGE_PIN H22 [get_ports {data_out[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_out[5]}]
set_property PACKAGE_PIN J22 [get_ports {data_out[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_out[6]}]
set_property PACKAGE_PIN K22 [get_ports {data_out[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_out[7]}]
set_property PACKAGE_PIN L22 [get_ports {data_out[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_out[8]}]
set_property PACKAGE_PIN M22 [get_ports {data_out[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_out[9]}]
set_property PACKAGE_PIN N22 [get_ports {data_out[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_out[10]}]
set_property PACKAGE_PIN P22 [get_ports {data_out[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_out[11]}]
set_property PACKAGE_PIN D23 [get_ports {data_out[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_out[12]}]

# Valid
set_property PACKAGE_PIN E23 [get_ports valid]
set_property IOSTANDARD LVCMOS18 [get_ports valid]
